# URL de conexión usando el Alias del TNS y la ruta interna del contenedor
spring.datasource.url=jdbc:oracle:thin:@trecml99m4zmwh47_high?TNS_ADMIN=/app/wallets

# Credenciales (Asegúrate que coincidan con las que usas en SQL Developer)
spring.datasource.username=FULLSTACK
spring.datasource.password=Full_1234567

# Driver y Wallet Location para Linux/Docker
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=(SOURCE=(METHOD=file)(METHOD_DATA=(DIRECTORY=/app/wallets)))

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true