spring.application.name=veterinaria-backend-clientes
server.port=8082

# Oracle Cloud Configuration
spring.datasource.url=jdbc:oracle:thin:@trecml99m4zmwh47_high?TNS_ADMIN=C:/Oci/wallets
# Credenciales (Asegúrate que coincidan con las que usas en SQL Developer)
spring.datasource.username=FULLSTACK
spring.datasource.password=Full_1234567

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=(SOURCE=(METHOD=file)(METHOD_DATA=(DIRECTORY=C:/Oci/wallets)))

# Reduce el pool al mínimo para desarrollo en la nube
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


