# ==========================================
# Backend Clientes - Docker / EC2
# ==========================================

spring.datasource.url=jdbc:oracle:thin:@trecml99m4zmwh47_high?TNS_ADMIN=/app/wallet

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=(SOURCE=(METHOD=file)(METHOD_DATA=(DIRECTORY=/app/wallet)))